In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('training_data.csv')

In [3]:
data

Age  Gender  Experience  Income
0   50       1          10     180
1   29       1          10     163
2   36       1           4     134
3   34       2           4     132
4   46       1           9     188
5   33       1           3     127
6   26       2           8     141
7   23       1           5     122
8   48       1           7     169
9   24       1           5     114

In [4]:
data_np = data.values # Convert pandas to numpy array

In [5]:
data_np

array([[ 50,   1,  10, 180],
       [ 29,   1,  10, 163],
       [ 36,   1,   4, 134],
       [ 34,   2,   4, 132],
       [ 46,   1,   9, 188],
       [ 33,   1,   3, 127],
       [ 26,   2,   8, 141],
       [ 23,   1,   5, 122],
       [ 48,   1,   7, 169],
       [ 24,   1,   5, 114]], dtype=int64)

In [6]:
# 종속변수와 독립변수 데이터 분리하기
y = data_np[:,-1]
X = data_np[:,:-1]

In [7]:
X

array([[50,  1, 10],
       [29,  1, 10],
       [36,  1,  4],
       [34,  2,  4],
       [46,  1,  9],
       [33,  1,  3],
       [26,  2,  8],
       [23,  1,  5],
       [48,  1,  7],
       [24,  1,  5]], dtype=int64)

In [8]:
y

array([180, 163, 134, 132, 188, 127, 141, 122, 169, 114], dtype=int64)

## Python에서 제공되는 sklearn을 사용하는 경우

In [9]:
import sklearn

In [10]:
sklearn.__version__

'0.23.2'

if not, pip install -U scikit-learn (관라자 모드로 cmd 실행)

In [11]:
from sklearn.linear_model import LinearRegression
#https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html

In [12]:
model = LinearRegression()
#model = LinearRegression(fit_intercept=False) => intercept를 사용하지 않고자 하는 경우

In [13]:
model.fit(X, y)

LinearRegression()

In [14]:
model.coef_

array([ 1.4935729 , -0.34682492,  5.80806575])

In [15]:
model.intercept_

57.538068443456055

# 새로운 데이터 예측하기

In [16]:
# 새로운 데이터 읽어오기
new_data = pd.read_csv('new_data.csv')

In [17]:
new_data

Age  Gender  Experience
0   45       1          10
1   33       2           6
2   32       1           4
3   39       2          15
4   41       1           9

In [18]:
X_new = new_data.values

In [19]:
X_new

array([[45,  1, 10],
       [33,  2,  6],
       [32,  1,  4],
       [39,  2, 15],
       [41,  1,  9]], dtype=int64)

In [20]:
model.predict(X_new) # 학습된 모델을 이용해서 y 값 예측하기

array([182.48268136, 140.98071869, 128.21783921, 202.2147478 ,
       170.70032402])

In [21]:
model.predict(np.array([30, 2, 1]).reshape(1,-1))

array([107.45967126])