In [1]:
import numpy as np

In [2]:
A = np.array([[5, 1],
            [3, 3]])

In [4]:
eigVals, eigVecs = np.linalg.eig(A)

In [5]:
eigVals

array([6., 2.])

In [6]:
eigVecs

array([[ 0.70710678, -0.31622777],
       [ 0.70710678,  0.9486833 ]])

In [7]:
v1 = eigVecs[:, 0]
v2 = eigVecs[:, 1]

In [8]:
v1

array([0.70710678, 0.70710678])

In [9]:
v2

array([-0.31622777,  0.9486833 ])

In [8]:
print(np.linalg.norm(v1))
print(np.linalg.norm(v2))

0.9999999999999999
0.9999999999999999


In [10]:
np.linalg.matrix_rank(A)

2

고유값과 행렬식의 관계

In [19]:
singular_mat = np.array([[1, 2],
                        [2, 4]])

In [20]:
np.linalg.eig(singular_mat)

(array([0., 5.]), array([[-0.89442719, -0.4472136 ],
        [ 0.4472136 , -0.89442719]]))

In [21]:
np.linalg.det(singular_mat)

0.0

In [22]:
np.linalg.matrix_rank(singular_mat)

1

In [23]:
np.linalg.inv(singular_mat)

LinAlgError: Singular matrix

대칭행렬의 고유벡터는 서로 수직

In [9]:
symm_mat = np.array([[1, 2],
                [2, 1]])

In [10]:
evalues, evectors= np.linalg.eig(symm_mat)

In [26]:
evectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [13]:
np.dot(evectors[:,0], evectors[:,1])

0.0

# Eigendecomposition

In [11]:
import numpy as np

In [12]:
A = np.array([[5, 1],
            [3, 3]])

In [14]:
eigVals, eigVecs = np.linalg.eig(A)

In [15]:
 eigVecs

array([[ 0.70710678, -0.31622777],
       [ 0.70710678,  0.9486833 ]])

In [16]:
V = eigVecs

In [17]:
V

array([[ 0.70710678, -0.31622777],
       [ 0.70710678,  0.9486833 ]])

In [18]:
eigVals

array([6., 2.])

In [20]:
Lamda = np.diag(eigVals)

In [21]:
Lamda

array([[6., 0.],
       [0., 2.]])

eigendecomposition

In [19]:
np.linalg.matrix_rank(V)

2

In [20]:
np.dot(V, Lamda).dot(np.linalg.inv(V))

array([[5., 1.],
       [3., 3.]])

### When A is a symmetric matrix, then A-1 = A.T

In [25]:
C = np.array([[5, 1],
            [1, 3]])

In [26]:
eigVals1, eigVecs1 = np.linalg.eig(C)

In [29]:
eigVecs1.T

array([[ 0.92387953,  0.38268343],
       [-0.38268343,  0.92387953]])

In [30]:
np.linalg.inv(eigVecs1)

array([[ 0.92387953,  0.38268343],
       [-0.38268343,  0.92387953]])