In [13]:
import numpy as np
np.set_printoptions(suppress=True)

A = np.array([[7, 2],
             [3, 4],
             [5, 3]])

np.dot(A, A.T) => 3x3 matrix, 고유값 3개 존재, 이중 하나의 값은 0 => 이에 해당하는 고유벡터는 사용하지 않는다.

In [7]:
U, D, V_T = np.linalg.svd(A, full_matrices=False)

In [8]:
U

array([[-0.69366543,  0.59343205],
       [-0.4427092 , -0.79833696],
       [-0.56818732, -0.10245245]])

In [9]:
D

array([10.25142677,  2.62835484])

In [10]:
V_T

array([[-0.88033817, -0.47434662],
       [ 0.47434662, -0.88033817]])

In [15]:
np.linalg.svd(A, full_matrices=True)[0] # U

array([[-0.69366543,  0.59343205, -0.40824829],
       [-0.4427092 , -0.79833696, -0.40824829],
       [-0.56818732, -0.10245245,  0.81649658]])

In [6]:
np.linalg.eig(A.dot(A.T))[1] # U corresponds to the eigenvectors of AAT

array([[-0.69366543, -0.59343205, -0.40824829],
       [-0.4427092 ,  0.79833696, -0.40824829],
       [-0.56818732,  0.10245245,  0.81649658]])

In [7]:
np.linalg.eig(A.T.dot(A))[1].T # V corresponds to the eigenvectors of ATA
# Scaling by -1 doesn’t change their direction or the fact that they are unit vectors.

array([[ 0.88033817,  0.47434662],
       [-0.47434662,  0.88033817]])

In [8]:
np.linalg.norm(np.linalg.eig(A.T.dot(A))[1].T[:,0]) # 각 vector의 norm = 1

0.9999999999999999

In [11]:
np.sqrt(np.linalg.eigvals(A.T.dot(A))) # D

array([10.25142677,  2.62835484])

In [11]:
np.sqrt(np.linalg.eigvals(A.dot(A.T)))

C:\Users\user\AppData\Local\Temp/ipykernel_17120/1537962928.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(np.linalg.eigvals(A.dot(A.T)))


array([10.25142677,  2.62835484,         nan])

In [14]:
np.linalg.eigvals(A.dot(A.T))

array([105.09175083,   6.90824917,  -0.        ])

In [19]:
np.dot(U,np.diag(D)).dot(V_T)

array([[7., 2.],
       [3., 4.],
       [5., 3.]])

In [7]:
import numpy as np
import pandas as pd

In [8]:
d = pd.read_csv('pca_data.csv', header = None)
# d = pd.read_excel('pca_data.xlsx', header = None)

In [9]:
d

0    1
0  2.5  2.4
1  0.5  0.7
2  2.2  2.9
3  1.9  2.2
4  3.1  3.0
5  2.3  2.7
6  2.0  1.6
7  1.0  1.1
8  1.5  1.6
9  1.1  0.9

In [10]:
d_np = d.values

In [11]:
U, D, V_T = np.linalg.svd(d_np, full_matrices=False)

In [12]:
U

array([[-0.38507927,  0.25575629],
       [-0.09481302, -0.17561812],
       [-0.40261598, -0.58718113],
       [-0.32307722, -0.19319469],
       [-0.4794398 ,  0.29239933],
       [-0.39407387, -0.27184299],
       [-0.28217662,  0.5344514 ],
       [-0.16535718, -0.04200527],
       [-0.24399096, -0.01146941],
       [-0.15681507,  0.27333287]])

In [13]:
D

array([8.98868529, 0.66598554])

In [14]:
V_T  

array([[-0.68647784, -0.72715072],
       [ 0.72715072, -0.68647784]])

## sklearn을 이용한 SVD (optional)

In [18]:
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(n_components=1, n_iter=100)
svd.fit_transform(d_np)

array([[3.46135634],
       [0.85224443],
       [3.61898835],
       [2.90403949],
       [4.30953348],
       [3.54220599],
       [2.53639684],
       [1.48634364],
       [2.19315792],
       [1.40956128]])

In [19]:
svd.components_ # 1st PC

array([[0.68647784, 0.72715072]])

In [20]:
svd.singular_values_ # 1st PC의 singular value

array([8.98868529])

In [21]:
np.dot(U,np.diag(D)).dot(V) # SVD 공식 확인

array([[2.5, 2.4],
       [0.5, 0.7],
       [2.2, 2.9],
       [1.9, 2.2],
       [3.1, 3. ],
       [2.3, 2.7],
       [2. , 1.6],
       [1. , 1.1],
       [1.5, 1.6],
       [1.1, 0.9]])

In [10]:
np.dot(U,np.diag(D))

array([[-3.46135634,  0.17032999],
       [-0.85224443, -0.11695913],
       [-3.61898835, -0.39105414],
       [-2.90403949, -0.12866487],
       [-4.30953348,  0.19473372],
       [-3.54220599, -0.1810435 ],
       [-2.53639684,  0.3559369 ],
       [-1.48634364, -0.0279749 ],
       [-2.19315792, -0.00763846],
       [-1.40956128,  0.18203574]])

In [11]:
V

array([[-0.68647784, -0.72715072],
       [ 0.72715072, -0.68647784]])

In [23]:
m = d_np.mean(axis = 0) # get mean of each column

In [24]:
centered_d = d_np - m

In [25]:
U, D, V = np.linalg.svd(centered_d, full_matrices=False) # PCA와 동일

In [15]:
np.dot(U,np.diag(D))

array([[-0.82797019,  0.17511531],
       [ 1.77758033, -0.14285723],
       [-0.99219749, -0.38437499],
       [-0.27421042, -0.13041721],
       [-1.67580142,  0.20949846],
       [-0.9129491 , -0.17528244],
       [ 0.09910944,  0.3498247 ],
       [ 1.14457216, -0.04641726],
       [ 0.43804614, -0.01776463],
       [ 1.22382056,  0.16267529]])