In [2]:
import pandas as pd
import numpy as np
iris = pd.read_csv('iris_data.csv')

In [3]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width     species
0           7.0          3.2           4.7          1.4  versicolor
1           6.4          3.2           4.5          1.5  versicolor
2           6.9          3.1           4.9          1.5  versicolor
3           5.5          2.3           4.0          1.3  versicolor
4           6.5          2.8           4.6          1.5  versicolor

In [4]:
iris_np = iris.values

In [5]:
iris_np

array([[7.0, 3.2, 4.7, 1.4, 'versicolor'],
       [6.4, 3.2, 4.5, 1.5, 'versicolor'],
       [6.9, 3.1, 4.9, 1.5, 'versicolor'],
       [5.5, 2.3, 4.0, 1.3, 'versicolor'],
       [6.5, 2.8, 4.6, 1.5, 'versicolor'],
       [5.7, 2.8, 4.5, 1.3, 'versicolor'],
       [6.3, 3.3, 4.7, 1.6, 'versicolor'],
       [4.9, 2.4, 3.3, 1.0, 'versicolor'],
       [6.6, 2.9, 4.6, 1.3, 'versicolor'],
       [5.2, 2.7, 3.9, 1.4, 'versicolor'],
       [5.0, 2.0, 3.5, 1.0, 'versicolor'],
       [5.9, 3.0, 4.2, 1.5, 'versicolor'],
       [6.0, 2.2, 4.0, 1.0, 'versicolor'],
       [6.1, 2.9, 4.7, 1.4, 'versicolor'],
       [5.6, 2.9, 3.6, 1.3, 'versicolor'],
       [6.7, 3.1, 4.4, 1.4, 'versicolor'],
       [5.6, 3.0, 4.5, 1.5, 'versicolor'],
       [5.8, 2.7, 4.1, 1.0, 'versicolor'],
       [6.2, 2.2, 4.5, 1.5, 'versicolor'],
       [5.6, 2.5, 3.9, 1.1, 'versicolor'],
       [5.9, 3.2, 4.8, 1.8, 'versicolor'],
       [6.1, 2.8, 4.0, 1.3, 'versicolor'],
       [6.3, 2.5, 4.9, 1.5, 'versicolor'],
       [6.1

In [6]:
iris_features = iris_np[:,:-1]
iris_labels = iris_np[:,-1]

In [7]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder() # categorical 변수의 값을 숫자로 변환하는데 사용
input_classes =['versicolor','virginica']
le.fit(input_classes)
iris_labels = le.transform(iris_labels)

In [8]:
iris_labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_features, iris_labels, test_size = 0.3, random_state=0)

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
lr_base = LogisticRegression(penalty='none')

In [12]:
lr_base.fit(X_train, y_train)

LogisticRegression(penalty='none')

In [13]:
y_predictions = lr_base.predict(X_test)

In [14]:
y_predictions

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1])

## Check model performance

In [15]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_predictions)

array([[13,  2],
       [ 0, 15]], dtype=int64)

In [16]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predictions))

              precision    recall  f1-score   support

           0       1.00      0.87      0.93        15
           1       0.88      1.00      0.94        15

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



# imbalanced classes

In [22]:
iris_imbalanced = pd.read_csv('iris_data_imbalanced.csv')

In [23]:
iris_np_imbalanced = iris_imbalanced.values

In [24]:
iris_features_imbalanced = iris_np_imbalanced[:,:-1]
iris_labels_imbalanced = iris_np_imbalanced[:,-1]

In [25]:
le = preprocessing.LabelEncoder() # categorical 변수의 값을 숫자로 변환하는데 사용
input_classes =['versicolor','virginica']
le.fit(input_classes)
iris_labels_imbalanced = le.transform(iris_labels_imbalanced)

In [26]:
print(iris_labels_imbalanced)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1]


In [39]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(iris_features_imbalanced, iris_labels_imbalanced, test_size = 0.3)

In [40]:
lr_base_imbalanced = LogisticRegression(penalty='none')

In [41]:
lr_base_imbalanced.fit(X_train1, y_train1)

LogisticRegression(penalty='none')

In [42]:
y_predictions_imbalanced = lr_base_imbalanced.predict(X_test1)

In [43]:
confusion_matrix(y_test1, y_predictions_imbalanced)

array([[61,  2],
       [ 1,  6]], dtype=int64)

In [44]:
print(classification_report(y_test1, y_predictions_imbalanced))

              precision    recall  f1-score   support

           0       0.98      0.97      0.98        63
           1       0.75      0.86      0.80         7

    accuracy                           0.96        70
   macro avg       0.87      0.91      0.89        70
weighted avg       0.96      0.96      0.96        70

