In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('training_test_data.csv')

In [3]:
data.head()

Age  Gender  Experience  Income
0   50       1          15     180
1   29       1           5     163
2   36       1           6     134
3   34       2           4     132
4   46       1           9     188

In [4]:
data_np = data.values

In [5]:
np.random.shuffle(data_np) #데이터를 random하게 다시 섞기

In [6]:
# 종속변수와 독립변수 데이터 분리하기
y = data_np[:,-1]
X = data_np[:,:-1]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [9]:
X_train.shape

(70, 3)

In [10]:
X_test.shape

(30, 3)

In [11]:
X_test

array([[52,  1, 24],
       [35,  1,  5],
       [22,  2,  1],
       [28,  1,  3],
       [47,  2, 18],
       [34,  1,  8],
       [50,  1, 20],
       [32,  1,  3],
       [24,  2,  2],
       [38,  2, 10],
       [41,  2, 15],
       [60,  1, 25],
       [47,  2, 21],
       [59,  1, 33],
       [37,  2, 10],
       [26,  2,  8],
       [22,  1,  1],
       [32,  1,  3],
       [57,  1, 31],
       [46,  1, 13],
       [39,  1,  6],
       [40,  1,  9],
       [43,  2, 17],
       [22,  1,  1],
       [28,  2,  2],
       [39,  1, 10],
       [33,  1,  7],
       [46,  2, 19],
       [24,  2,  1],
       [23,  2,  3]], dtype=int64)

## Feature scaling

### standardization

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [13]:
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

In [14]:
X_train_std

array([[ 1.39693814, -1.02899151,  1.61840786],
       [-0.91233256, -1.02899151, -0.9584235 ],
       [ 0.91915799,  0.97182532,  0.42202187],
       [-1.07159261,  0.97182532, -0.9584235 ],
       [-0.19566234,  0.97182532, -0.13015628],
       [-0.75307251,  0.97182532, -0.9584235 ],
       [ 0.04322773, -1.02899151,  0.05390311],
       [-0.67344249,  0.97182532, -0.77436412],
       [ 0.52100787, -1.02899151, -0.31421566],
       [-0.51418244, -1.02899151, -0.59030474],
       [ 0.36174782, -1.02899151,  0.32999218],
       [ 0.83952797, -1.02899151,  0.79014064],
       [ 1.39693814,  0.97182532,  1.52637817],
       [-1.39011271, -1.02899151, -1.05045319],
       [ 0.52100787, -1.02899151, -0.03812659],
       [-1.07159261,  0.97182532, -0.9584235 ],
       [-1.46974273,  0.97182532, -1.05045319],
       [-0.83270254, -1.02899151, -0.68233443],
       [ 1.39693814,  0.97182532,  1.43434848],
       [-0.75307251,  0.97182532, -1.05045319],
       [ 1.39693814, -1.02899151,  1.618

In [15]:
X_test_std

array([[-0.95883727, -0.94440028, -0.68061641],
       [-0.47010953,  1.05887304, -0.87350365],
       [-0.22574567, -0.94440028, -0.58417279],
       [-0.7144734 ,  1.05887304, -1.0663909 ],
       [ 1.4848014 ,  1.05887304,  1.63403049],
       [ 0.91461904,  1.05887304,  0.86248153],
       [ 1.15898291,  1.05887304,  1.34469963],
       [-1.36611038, -0.94440028, -1.0663909 ],
       [ 0.18152744,  1.05887304,  0.2838198 ],
       [-1.04029189,  1.05887304, -0.39128555],
       [ 0.99607367,  1.05887304,  0.47670704],
       [ 1.4848014 , -0.94440028,  1.73047412],
       [ 0.91461904, -0.94440028,  0.7660379 ],
       [-0.87738264,  1.05887304, -0.96994727],
       [ 0.0186182 , -0.94440028, -0.19839831],
       [-1.04029189, -0.94440028, -1.0663909 ],
       [ 1.4848014 ,  1.05887304,  1.63403049],
       [-0.14429104, -0.94440028, -0.10195469],
       [-0.79592802, -0.94440028, -0.96994727],
       [ 0.7517098 , -0.94440028, -0.48772917],
       [-1.20320113,  1.05887304, -1.066

In [19]:
from sklearn.linear_model import LinearRegression
model_std = LinearRegression()

In [17]:
model_std.fit(X_train_std, y_train)

LinearRegression()

In [18]:
model_std.score(X_test_std, y_test)

0.6188011358404542

### min-max scaling

In [15]:
from sklearn.preprocessing import MinMaxScaler
scaler_minmax = MinMaxScaler()

In [16]:
X_train_minmax = scaler_minmax.fit_transform(X_train)
X_test_minmax = scaler_minmax.transform(X_test)

In [17]:
X_test_minmax

array([[0.79487179, 0.        , 0.72727273],
       [0.35897436, 0.        , 0.15151515],
       [0.02564103, 1.        , 0.03030303],
       [0.17948718, 0.        , 0.09090909],
       [0.66666667, 1.        , 0.54545455],
       [0.33333333, 0.        , 0.24242424],
       [0.74358974, 0.        , 0.60606061],
       [0.28205128, 0.        , 0.09090909],
       [0.07692308, 1.        , 0.06060606],
       [0.43589744, 1.        , 0.3030303 ],
       [0.51282051, 1.        , 0.45454545],
       [1.        , 0.        , 0.75757576],
       [0.66666667, 1.        , 0.63636364],
       [0.97435897, 0.        , 1.        ],
       [0.41025641, 1.        , 0.3030303 ],
       [0.12820513, 1.        , 0.24242424],
       [0.02564103, 0.        , 0.03030303],
       [0.28205128, 0.        , 0.09090909],
       [0.92307692, 0.        , 0.93939394],
       [0.64102564, 0.        , 0.39393939],
       [0.46153846, 0.        , 0.18181818],
       [0.48717949, 0.        , 0.27272727],
       [0.

In [20]:
model_minmax = LinearRegression()
model_minmax.fit(X_train_minmax, y_train)

LinearRegression()

In [91]:
model_minmax.score(X_test_minmax, y_test)

0.6682911567046792