In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer # frequency based DTM
from sklearn.feature_extraction.text import TfidfVectorizer # tf-idf based DTM

In [2]:
TEXT = ['banana apple apple eggplant', 
        'orange carrot banana eggplant', 
        'apple carrot banana banana', 
        'orange banana grape'
]

# CountVectorizer 이용하기

In [3]:
tf_vectorizer = CountVectorizer()
tf_features = tf_vectorizer.fit_transform(TEXT)

In [4]:
tf_features

<4x6 sparse matrix of type '<class 'numpy.int64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [5]:
features = np.array(tf_features.todense())
features

array([[2, 1, 0, 1, 0, 0],
       [0, 1, 1, 1, 0, 1],
       [1, 2, 1, 0, 0, 0],
       [0, 1, 0, 0, 1, 1]], dtype=int64)

In [6]:
features.shape

(4, 6)

In [7]:
features

array([[2, 1, 0, 1, 0, 0],
       [0, 1, 1, 1, 0, 1],
       [1, 2, 1, 0, 0, 0],
       [0, 1, 0, 0, 1, 1]], dtype=int64)

In [8]:
features[0]

array([2, 1, 0, 1, 0, 0], dtype=int64)

In [9]:
features[1]

array([0, 1, 1, 1, 0, 1], dtype=int64)

In [10]:
np.linalg.norm(features[1]-features[0])

2.449489742783178

In [9]:
np.linalg.norm(features[1]-features[0])

2.449489742783178

In [10]:
np.linalg.norm(features[1]-features[2])

2.0

In [11]:
np.dot(features[0], features[1])/(np.linalg.norm(features[0])*np.linalg.norm(features[1]))

0.4082482904638631

In [12]:
np.dot(features[0], features[2])/(np.linalg.norm(features[0])*np.linalg.norm(features[2]))

0.6666666666666667

In [11]:
feature_names = tf_vectorizer.get_feature_names_out()
feature_names

array(['apple', 'banana', 'carrot', 'eggplant', 'grape', 'orange'],
      dtype=object)

In [12]:
import pandas as pd
df = pd.DataFrame(data=features, columns=feature_names)
print(df)

   apple  banana  carrot  eggplant  grape  orange
0      2       1       0         1      0       0
1      0       1       1         1      0       1
2      1       2       1         0      0       0
3      0       1       0         0      1       1


# TfidfVectorizer 이용하기

In [13]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_features = tfidf_vectorizer.fit_transform(TEXT)

In [14]:
tfidf_features = np.array(tfidf_features.todense())
tfidf_features

array([[0.85764287, 0.28383251, 0.        , 0.42882143, 0.        ,
        0.        ],
       [0.        , 0.35696573, 0.53931298, 0.53931298, 0.        ,
        0.53931298],
       [0.51623315, 0.68337886, 0.51623315, 0.        , 0.        ,
        0.        ],
       [0.        , 0.37919167, 0.        , 0.        , 0.72664149,
        0.5728925 ]])

In [15]:
tfidf_features.shape

(4, 6)

In [16]:
tfidf_features[0]

array([0.85764287, 0.28383251, 0.        , 0.42882143, 0.        ,
       0.        ])